---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  N2-bh + vlan 903 + core_sriov_netdevice
###############################################################################
# NS =
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: n2-bh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: core_netdevice
  networkNamespace: open5gs-core
  vlan: 903
  ipam: |-
    {"type": "static"}
  linkState: auto
