---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  s1c-bh + vlan 803 + core_sriov_netdevice
###############################################################################
# NS = open5gs-core
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: s1cbh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: core_sriov_netdevice
  networkNamespace: open5gs-core
  vlan: 905
  ipam: |-
    {
      "type": "static",
      "addresses": [
        {
          "address": "10.28.5.8/24",
          "gateway": "10.28.5.1"
        },
        {
          "address": "fd00:6:6:905::8/64"
          "gateway": "fd00:6:6:905::1"
        }
      ]
    }
  linkState: auto
