---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  N2-bh + vlan 823 + core_sriov_netdevice
###############################################################################
# NS = open5gs-core
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: n2bh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: core_sriov_netdevice
  networkNamespace: open5gs-core
  vlan: 823
  ipam: |-
    {
      "type": "static",
      "addresses": [
        {
          "address": "10.28.3.8/24",
          "gateway": "10.28.3.1"
        },
        {
          "address": "fd00:6:6:823::8/64",
          "gateway": "fd00:6:6:823::1"
        }
      ]
    }
  linkState: auto
