---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  s1u-bh + vlan 826 + core_sriov_netdevice
###############################################################################
# NS = open5gs-core
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: s1ubh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: core_sriov_netdevice
  networkNamespace: open5gs-core
  vlan: 826
  ipam: |-
    {
      "type": "static",
      "addresses": [
        {
          "address": "10.28.6.8/24",
          "gateway": "10.28.6.1"
        },
        {
          "address": "fd00:6:6:826::8/64",
          "gateway": "fd00:6:6:826::1"
        }
      ]
    }
  linkState: auto
