---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  s1c-bh + vlan 803 + core_sriov_netdevice
###############################################################################
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: s1c-bh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: core_netdevice
  networkNamespace: open5gs-core
  vlan: 803
  ipam: |-
    {"type": "static"}
  linkState: auto