---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  N3-bh + vlan 904 + core_sriov_netdevice
###############################################################################
# NS = open5gs-core
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: n3bh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: core_sriov_netdevice
  networkNamespace: open5gs-core
  vlan: 904
  ipam: |-
    {
      "type": "static",
      "addresses": [
        {
          "address": "10.28.4.8/24",
          "address": "10.28.4.1"
        },
        {
          "address": "fd00:6:6:904::8/64",
          "gateway": "fd00:6:6:904::1"
        }
      ]
    }
  linkState: auto
