---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  n6 + vlan 2020 + vran_netdevice
###############################################################################
# NS = workload-n6-backhaul
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: n6-wan
  namespace: openshift-sriov-network-operator
spec:
  resourceName: core_netdevice
  networkNamespace: open5gs-core
  vlan: 2020
  ipam: |-
    {"type": "static"}
  linkState: auto