---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
#  s1c-bh + vlan 2013 + vran_netdevice
###############################################################################
# NS = workload-s1-backhaul
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: s1c-bh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice
  networkNamespace: open5gs-core
  vlan: 2013 
  ipam: |-
    {"type": "static"}
  linkState: auto