apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open5gs-core
generatorOptions:
  labels:
    app.kubernetes.io/part-of: open5gs
    name: smf
  disableNameSuffixHash: true
configMapGenerator:
- name: smf
  files:
    - smf.conf
    - smf.yaml
