logger:
    file: /var/log/open5gs/smf.log

parameter:

smf:
    freeDiameter: /etc/freeDiameter/smf.conf
    sbi:
      - dev: eth0
        port: 7777
    gtpc:
      - addr: 0.0.0.0
    gtpu:
      - addr: 0.0.0.0
    pfcp:
      - addr: 0.0.0.0
    subnet:
      - addr: 45.45.0.1/24
        dnn: internet
    dns:
      - 8.8.8.8
      - 8.8.4.4
    mtu: 1400

nrf:
    sbi:
      - name: nrf
        port: 7777
upf:
    pfcp:
      - addr: $UPFIP
