logger:
    file: /var/log/open5gs/smf.log

parameter:

smf:
    freeDiameter: /open5gs/install/etc/freeDiameter/smf.conf
    sbi:
      - addr: 172.30.1.14
        port: 7777
    gtpc:
      - addr: 172.30.1.14
    gtpu:
      - addr: 172.30.1.14
    pfcp:
      - addr: 172.30.1.14
    subnet:
      - addr: 45.45.0.1/24
        dnn: internet
        dev: ogstun
    dns:
      - 8.8.8.8
      - 8.8.4.4
    mtu: 1400

nrf:
    sbi:
      - addr:
          - 172.30.1.13
        port: 7777

upf:
    pfcp:
      - addr: 172.30.1.8
