apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open5gs-core
generatorOptions:
  labels:
    app.kubernetes.io/part-of: open5gs
    name: upf
  disableNameSuffixHash: true
configMapGenerator:
- name: upf
  files:
    - upf.yaml
