logger:
    file: /var/log/open5gs/ugf.log
    trace:
        app: 1
        diameter: 1
        gtpv2: 1
        gtp: 1
        
parameter:

upf:
    pfcp:
      - dev: eth0
    gtpu:
      - dev: net1
    subnet:
      - addr: 45.45.0.0/16
        dev: ogstun
        dnn: internet