#!/bin/sh
set -o errexit

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")") 

HERE=$HERE \
envsubst < "$HERE/manifests/kind/kind-cluster.yaml" |
kind create cluster --config=-
#kind create cluster --config=$HERE/manifests/kind/kind-cluster.yaml

#prepare nodes
for NODE in kind-control-plane kind-worker kind-worker2 kind-worker3 
do
	docker exec -it $NODE ip link add data-plane-vlan link eth0 type macvlan mode bridge 
	docker exec -it $NODE ip link set data-plane-vlan up
done