#!/bin/sh
set -o errexit

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")") 

SCRIPT=$(readlink -f $0)
SPATH=`dirname $SCRIPT`

echo "path is "$SPATH

HERE=$HERE \
SPATH=$SPATH \
envsubst < "$HERE/manifests/kind/kind-cluster.yaml" |
kind create cluster --config=-

#prepare nodes
for NODE in kind-control-plane kind-worker kind-worker2 kind-worker3 
do
	docker exec -it $NODE ip link add data-plane-vlan link eth0 type macvlan mode bridge 
	docker exec -it $NODE ip link set data-plane-vlan up
done
