logger:
    file: /var/log/open5gs/sgwc.log
    trace:
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

sgwc:
    gtpc:
      - addr: 0.0.0.0
    pfcp:
      - addr: 0.0.0.0
      
sgwu:
    pfcp:
      - addr: sgwu
