logger:
    file: /var/log/open5gs/nssf.log

parameter:

nssf:
    sbi:
      - dev: eth0
        port: 7777
    nsi:
      - name: nrf
        port: 7777
        s_nssai:
          sst: 1
nrf:
    sbi:
      - name: nrf
        port: 7777
