apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-vol1
  namespace: mongodb
  labels:
    app.kubernetes.io/name: open5gs-mongodb
    app.kubernetes.io/instance: open5gs-mongodb
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /
    server: 10.40.0.101
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-altreg
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-vol2
  namespace: mongodb
  labels:
    app.kubernetes.io/name: open5gs-mongodb
    app.kubernetes.io/instance: open5gs-mongodb
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /
    server: 10.40.0.101
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-altreg
  volumeMode: Filesystem
