---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity

metadata:
  name: open5gs-mongodb
  labels:
    app.kubernetes.io/name: open5gs-mongodb
    app.kubernetes.io/instance: open5gs-mongodb
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs

spec:
  type: ReplicaSet
  members: 1
  version: $MONGODB_VERSION
  security:
    authentication:
      modes: ["SCRAM-SHA-1"]
  users:
  - name: user
    db: admin
    passwordSecretRef:
      name: open5gs-mongodb-user-password
    roles:
    - name: clusterAdmin
      db: admin
    - name: userAdminAnyDatabase
      db: admin
    - name: readWriteAnyDatabase
      db: admin
    scramCredentialsSecretName: scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    storage.wiredTiger.engineConfig.cacheSizeGB: 0.25
  # The defaults are 10GB persistent volume claims
  statefulSet:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: open5gs-mongodb
        selector:
          matchLabels:
            app.kubernetes.io/name: open5gs-mongodb
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 1100m
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 200Mi
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            - name: mongodb-agent
              resources:
                limits:
                  cpu: 1100m
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 200Mi
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: feature.node.kubernetes.io/open5gs
                    operator: In
                    values:
                      - "true"
      volumeClaimTemplates:
      - metadata:
          name: data-volume
          labels:
            app.kubernetes.io/name: open5gs-mongodb
            app.kubernetes.io/instance: open5gs-mongodb-data
            app.kubernetes.io/component: 5g
            app.kubernetes.io/part-of: open5gs
            app.kubernetes.io/managed-by: open5gs
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "nfs-altreg"
          resources:
            requests:
              storage: 2Gi
      - metadata:
          name: logs-volume
          labels:
            app.kubernetes.io/name: open5gs-mongodb
            app.kubernetes.io/instance: open5gs-mongodb-logs
            app.kubernetes.io/component: 5g
            app.kubernetes.io/part-of: open5gs
            app.kubernetes.io/managed-by: open5gs
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "nfs-altreg"
          resources:
            requests:
              storage: 2Gi
---
apiVersion: v1
kind: Secret

metadata:
  name: open5gs-mongodb-user-password

type: Opaque
stringData:
  password: password
