apiVersion: v1
data:
  pcf.yaml: |
    db_uri: $MONGODB_URI

    logger:
        file: /var/log/open5gs/pcf.log

    parameter:

    pcf:
        sbi:
          - dev: eth0
            port: 7777

    nrf:
        sbi:
          - name: nrf
            port: 7777
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-05T15:48:00Z"
  labels:
    app.kubernetes.io/part-of: open5gs
    name: pcf
  name: pcf
  namespace: $NS
