apiVersion: v1
data:
  sgwc.yaml: |
    logger:
        file: /var/log/open5gs/sgwc.log
    sgwc:
        gtpc:
          dev: eth0
        pfcp:
          dev: eth0
    sgwu:
        pfcp:
          name: sgwu
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-05T15:34:27Z"
  labels:
    app.kubernetes.io/part-of: open5gs
    name: sgwc
  name: sgwc
  namespace: $NS