apiVersion: v1
data:
  sgwu.yaml: |
    logger:
        file: /var/log/open5gs/sgwu.log

    sgwu:
        gtpu:
           dev: eth0
        pfcp:
           dev: eth0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: open5gs
    name: sgwu
  name: sgwu
  namespace: $NS
