apiVersion: v1
kind: ConfigMap
metadata:
  name: udm
  namespace: $NS
  labels:
    app.kubernetes.io/part-of: open5gs
data:
  udm.yaml: |
    logger:
    file: /var/log/open5gs/udm.log

    parameter:

    udm:
        sbi:
          - dev: eth0
            port: 7777

    nrf:
        sbi:
          - name: nrf
            port: 7777
