apiVersion: v1
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log
        level: debug

    parameter:
        no_ipv6: true

    upf:
        pfcp:
          - dev: eth0
        gtpu:
          - dev: eth0
        subnet:
          - addr: 45.45.0.0/16
            dev: ogstun
            dnn: internet
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: open5gs
    name: upf
  name: upf
  namespace: $NS