apiVersion: v1
data:
  wraprouting: "#!/bin/sh\n\nset -euo pipefail\n\necho \"Do upf routing initialization
    then run open5gs entrypoint\"\n \ndnf -y install iproute \\\niptables\n\nip tuntap
    add name ogstun mode tun;\nip addr add 45.45.0.10/16 dev ogstun;\nip link set
    ogstun mtu 1450;\nip link set ogstun up;\nsh -c \"echo 1 > /proc/sys/net/ipv4/ip_forward\";\n\niptables
    -t nat -A POSTROUTING -s 45.45.0.0/16 ! -o ogstun -j MASQUERADE;\niptables -A
    INPUT -i ogstun -j ACCEPT;\n\nexec /bin/open5gs\n"
kind: ConfigMap
metadata:
  name: wraprouting
  labels:
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs
  name: wraprouting
  namespace: $NS