---
# This net-attach-def define a user-plane-vlan configuration 
# +ip cababilities to specify the ip address in pod annotation
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: user-plane-vlan
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true},
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "subnet": "192.168.3.0/24",
            "rangeStart": "192.168.3.200",
            "rangeEnd": "192.168.3.216",
            "routes": [
              { 
                "dst": "0.0.0.0/0",
                "gw": "192.168.3.1" 
              }   
            ]
          }
        }
      ]
  }'
---
# This net-attach-def define a user-plane-vlan configuration 
# +ip cababilities to specify the ip address in pod annotation
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ctrl-plane-vlan
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true},
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "subnet": "192.168.4.0/24",
            "rangeStart": "192.168.4.200",
            "rangeEnd": "192.168.4.216",
            "routes": [
              { 
                "dst": "0.0.0.0/0",
                "gw": "192.168.4.1" 
              }   
            ]
          }
        }
      ]
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ 
            { 
              "name": "user-plane-vlan", 
              "interface": "u-plane",
              "ips": ["192.168.3.201/24"],
              "mac": "c2:b0:57:49:03:f1",
              "gateway": [ "192.168.3.1" ]
            },
            {
              "name": "ctrl-plane-vlan", 
              "interface": "c-plane",
              "ips": ["192.168.4.201/24"],
              "gateway": [ "192.168.4.1" ]
            }
          ]'
spec:
  containers:
  - name: samplepod1
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ 
            { 
              "name": "user-plane-vlan", 
              "interface": "u-plane",
              "ips": ["192.168.3.202/24"],
              "mac": "c2:b0:57:49:03:f2",
              "gateway": [ "192.168.3.1" ]
            },
            {
              "name": "ctrl-plane-vlan",
              "interface": "c-plane",
              "ips": ["192.168.4.202/24"],
              "gateway": ["192.168.4.1"]
            }
          ]'
spec:
  containers:
  - name: samplepod2
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
