apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ 
            { "name": "user-plane-vlan", 
              "interface": "u-p",
              "ips": ["192.168.3.201/24"],
              "mac": "c2:b0:57:49:47:f1",
              "gateway": [ "192.168.3.1" ]
            }]'
spec:
  containers:
  - name: samplepod1
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
