apiVersion: v1
kind: Pod
metadata:
  name: samplepod2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ 
            { 
              "name": "user-plane-vlan", 
              "interface": "u-plane",
              "ips": ["192.168.3.202/24"],
              "mac": "c2:b0:57:49:47:f2",
              "gateway": [ "192.168.3.1" ]
            },
            {
              "name": "ctrl-plane-vlan",
              "interface": "c-plane",
              "ips": ["192.168.4.202/24"],
              "gateway": ["192.168.4.1"]
            }
          ]'
spec:
  containers:
  - name: samplepod2
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
