#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")

. "$HERE/../../_functions"

m 'Multus: deploy network attachment definition' "$GREEN"

kubectl apply -f example.yml

m 'deploy samplepods' "$GREEN"
