db_uri: mongodb://172.30.1.12/open5gs

logger:
    file: /var/log/open5gs/pcf.log

parameter:

pcf:
    sbi:
      - addr: 172.30.1.15
        port: 7777

nrf:
    sbi:
      - addr:
          - 172.30.1.17
        port: 7777