logger:
    file: /var/log/open5gs/sgwu.log
    trace:
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

sgwu:
    gtpu:
      - addr: 0.0.0.0
        advertise: 0.0.0.0
    pfcp:
      - addr: 0.0.0.0

sgwc:
    pfcp:
      - name: sgwc
