logger:
    file: /var/log/open5gs/sgwu.log
    trace:
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

sgwu:
    gtpu:
      - addr: 172.30.1.7
        advertise: 172.30.1.7
    pfcp:
      - addr: 172.30.1.7

sgwc:
    pfcp:
      - addr: 172.30.1.6